### ISSUE TITLE
ds-error is not setting field to invalid

### ISSUE THREAD

**Issue by henriquecf** [offirgolan/ember-cp-validations#373] opened 2016-10-17 20:08 UTC
### Environment
- Ember Version: 2.8.1
- Ember CLI Version: 2.8.0
- Ember CP Validations Version: 3.1.0
### Steps to Reproduce

Hello, I am using ds-error to catch some errors that are difficult to validate on ember, and it is getting the error message as expected. But the problem is that, when there is an error from ds-error, the field being validated does is not set to invalid.

**Comment by offirgolan** [comment] 2016-11-01 02:46
Hi there. That's a pretty weird issue. Any chance you can replicated it so I can debug it?

**Comment by riklaunim** [comment] 2016-11-09 12:21
Same for me after upgrading to ember-cp-validations 3.1.2 (from 2.X) and ember/ember-data 2.9. Also using ember-intl-cp-validations 2.3.1. 

Django RestFramework jsonapi responds with usuall 422 error response:
```
[{"source":{"pointer":"/data/attributes/image"},"detail":"The type of the image couldn't be determined.","status":"422"}]
```
Yet, field is valid.

**Comment by riklaunim** [comment] 2016-11-09 12:40
What I also found is that model.isValid is true when backend reports those errors ( http://emberjs.com/api/data/classes/DS.Model.html#property_isValid ).

I was using modelValid=(get someModel 'isValid') in one of my components to not display error messages for new create forms (a.k.a. "this field is required" and alike). 

What works now is isError - http://emberjs.com/api/data/classes/DS.Model.html#property_isError whereas behavior of isError and isValid contradicts their description.

**Comment by offirgolan** [comment] 2016-11-09 12:42
@riklaunim are you accessing the correct validation fields?

```
model.get('validations.attrs.image.isValid');
model.get('validations.attrs.image.message');
```

**Comment by riklaunim** [comment] 2016-11-09 12:43
That part is correct - i get cp-validations error messages (is required and this date after that date), but not backend ones.

**Comment by offirgolan** [comment] 2016-11-09 12:45
@riklaunim I'm not sure I'm following. Can show me a snippet of your model validations?

**Comment by riklaunim** [comment] 2016-11-09 12:46
I think I found the cause - using ember-ajax for JSONAPIAdapter is breaking the errors from backend to pass through.

**Comment by henriquecf** [comment] 2016-12-12 18:40
For what I have seen the only thing that the ds-error validator does is to set the validation from ember-data as a dependent key.

I think this may be the reason why the isValid option is not set to false when the validation from the backend fails... does it make sense?

**Comment by offirgolan** [comment] 2016-12-12 22:03
@henriquecf [its also grabs the most recent error message for the attribute](https://github.com/offirgolan/ember-validators/blob/master/addon/ds-error.js#L32-L42)

**Comment by offirgolan** [comment] 2017-05-31 08:28
Closing as this issue has been abandoned. Feel free to reopen if needed.

**Closed by offirgolan** 2017-05-31 08:28 UTC
