### ISSUE TITLE
DEPRECATION: An addon is trying to access project.nodeModulesPath

### ISSUE THREAD

**Issue by tarponjargon** [offirgolan/ember-cp-validations#562] opened 2018-02-08 05:13 UTC
### Environment

- Ember Version: 2.18
- Ember CLI Version: 2.18.2
- Ember CP Validations Version: 3.5.1

### Steps to Reproduce

```
ember new ember-quickstart
cd ember-quickstart
ember i ember-cp-validations
ember s
```

Output in console:

`DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   NPMDependencyVersionChecker (/Users/rory/Desktop/ember-quickstart/node_modules/ember-string-ishtmlsafe-polyfill/node_modules/ember-cli-version-checker/src/npm-dependency-version-checker.js:11:32)
`

```
npm ls ember-string-ishtmlsafe-polyfill
ember-quickstart@0.0.0 /Users/rory/Desktop/ember-quickstart
└─┬ ember-cp-validations@3.5.1
  └── ember-string-ishtmlsafe-polyfill@2.0.0
```

I attempted to do a PR following [these directions](https://discuss.emberjs.com/t/deprecation-warning-for-addons-future-big-problems/14204/4) but didn't have any luck :-/

**Comment by offirgolan** [comment] 2018-02-10 02:08
Hi @tarponjargon, this is actually coming from `ember-string-ishtmlsafe-polyfill` and not from this addon. I would suggest making that change there.

Im gonna go ahead and close this issue since it's a duplicate of #559.

**Closed by offirgolan** 2018-02-10 02:08 UTC

**Comment by offirgolan** [comment] 2018-02-10 05:29
This addon is since it support Ember 1.11+. That will be removed when #564 gets merged and released though so stay tuned.

**Comment by tarponjargon** [comment] 2018-02-10 05:33
I gotcha - thanks for explaining
