### ISSUE TITLE
DEPRECATION: An addon is trying to access project.nodeModulesPath.

### ISSUE THREAD

**Issue by jnfingerle** [offirgolan/ember-cp-validations#559] opened 2018-01-23 13:28 UTC
The current CP-Validations 3.5.1 leads in Ember 2.18 to a deprecation warning.

### Environment

- Ember Version: 2.18.0
- Ember CLI Version: 2.18.1
- Ember CP Validations Version: 3.5.1
- node: 6.3.1

### Steps to Reproduce
```
T:\>ember addon test-cp-val
installing addon
[...]

T:\>cd test-cp-val

T:\test-cp-val>ember install ember-cp-validations
npm: Installed ember-cp-validations
installing ember-cp-validations
Installed addon package.

T:\test-cp-val>ember test
DEPRECATION: An addon is trying to access project.nodeModulesPath. This is not a reliable way to discover npm modules. Instead, consider doing: require("resolve").sync(something, { basedir: project.root }). Accessed from:   DependencyVersionChecker.NPMDependencyVersionChecker (T:\test-cp-val\node_modules\ember-string-ishtmlsafe-polyfill\node_modules\ember-cli-version-checker\src\npm-dependency-version-checker.js:11:32)
cleaning up...
Built project successfully. Stored in "T:\test-cp-val\tmp\class-tests_dist-2jDNenX4.tmp".
ok 1 Chrome 63.0 - ESLint | app: app.js
ok 2 Chrome 63.0 - ESLint | app: resolver.js
ok 3 Chrome 63.0 - ESLint | app: router.js
ok 4 Chrome 63.0 - ESLint | tests: helpers/destroy-app.js
ok 5 Chrome 63.0 - ESLint | tests: helpers/module-for-acceptance.js
ok 6 Chrome 63.0 - ESLint | tests: helpers/start-app.js
ok 7 Chrome 63.0 - ESLint | tests: test-helper.js
ok 8 Chrome 63.0 - ember-qunit: Ember.onerror validation: Ember.onerror is functioning properly

1..8
# tests 8
# pass  8
# skip  0
# fail  0

# ok
```

**Comment by rwjblue** [comment] 2018-01-23 13:45
Based on the message you shared, the issue is not with ember-cp-validations but instead with ember-string-ishtmlsafe-polyfill's version of ember-cli-version-checker.  Probably best to send a PR over there to bump it to a more recent version...

**Comment by offirgolan** [comment] 2018-02-10 02:10
Thanks for chiming in @rwjblue! Im gonna go ahead and close this issue.

**Closed by offirgolan** 2018-02-10 02:10 UTC
