### ISSUE TITLE
Validations on same model across multi-page and routed form

### ISSUE THREAD

**Issue by gosseti** [offirgolan/ember-cp-validations#519] opened 2017-07-27 07:00 UTC
### Environment

- Ember Version: 2.13.3
- Ember CLI Version: 2.13.3
- Ember CP Validations Version: 3.3.2

### Steps to Reproduce

Not so much a bug to report or anything, just a bit stuck on how to achieve route-specific validations on the same model. I have a routed checkout system spread across several pages: 

- `checkout.info`: for which I’d like to only validate `name` and `email`
- `checkout.shipping`: for which I’d like to only validate `address1`, `state`, `zipCode` etc.

All of these fields are part of the same `order` model.

How might I go about doing this?

**Comment by erzzo** [comment] 2017-09-26 15:17
I'm struggling with the same problem. I'm using validations on a component to change a forgotten user password (it's a little bit simplified):

```javascript
{{#paper-form 
	isTouched=(readonly isSubmitted) 
	onSubmit=(action "onSubmit") as |form|
}}
	{{form.input 
		type="password"
		label="Password"
		value=password
		errors=validations.attrs.password.messages
		onChange=(action (mut password))
	}}
	{{#form.submit-button
		primary=true
		raised=true
	}}Submit{{/form.submit-button}}
{{/paper-form}}
```

component:

```javascript
export default Ember.Component.extend(Validations, {
	actions: {
		onSubmit() {
			this.set('isSubmitted', true);

			if (this.get('validations.isInvalid')) {return;}

			this.set('password', '');
                        someFunc();
		}
	}
});

```

basic user model:
```javascript
export default DS.Model.extend(Validations, {
	email: DS.attr('string')
});

```

validations: 

```javascript
buildValidations({	
	email: {
		description: 'Email',
		validators: [
			validator('presence', {presence: true}),
			validator('format', {type: 'email'})
		]
	},
	password: {
		description: 'Password',
		validators: [
			validator('presence', {presence: true}),
			validator('length', {min: 5})
		]
	},
});
```

The problem is (is it?) when I submit the form the first time the `validations.isValid` says `true`. When I try it the second time it's `false`. Is this a normal behavior?

My solution was to check directly the `password` property:

```javascript
if (this.get('validations.attrs.password.isInvalid')) {return;}
```

So @gosseti you can do it this way, but go through every property that you need check per specific route.

Is this problem what I described a problem? And is there a better way to do that?

**Comment by offirgolan** [comment] 2017-11-14 16:23
Closing as this issue has been abandoned. Feel free to reopen if needed.

**Closed by offirgolan** 2017-11-14 16:23 UTC
Labels: question
